
# Reads from ia_video_metadata2.csv and fm_item_questions2.csv
# These questions are designed for inputting the Lateralities individually (use human-selected camera angles)
# So we do not have the direct comparisons of the two sides.

# Load StrokeRehab dataset from local
dataset_kwargs:
  use_dataset_builder: !function utils_impairment_analysis.load_sria2_3_30
task: "strokerehab_ia2_3_30"
test_split: test
output_type: generate_until
doc_to_visual: !function utils_impairment_analysis.sr_ia_doc_to_visual
doc_to_text: !function utils_impairment_analysis.sr_ia_doc_to_text2
doc_to_target: !function utils_impairment_analysis.sr_ia_doc_to_target
generation_kwargs:
  max_new_tokens: 16  # Can be increase
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils_impairment_analysis.sr_ia_process_results2
filter_list:
  - name: "combine-and-parse"
    filter:
      - function: !function utils_impairment_analysis.OutputToResultsFilter
metadata:
  version: 1.0
