# Load StrokeRehab dataset from local
dataset_kwargs:
  use_dataset_builder: !function utils.strokerehab_load_summarization_data
task: "strokerehab_describe"
test_split: test
output_type: generate_until
doc_to_visual: !function utils_describe.sr_describe_doc_to_visual
doc_to_text: !function utils_describe.sr_describe_doc_to_text
doc_to_target: !function utils_describe.sr_describe_doc_to_target
generation_kwargs:
  max_new_tokens: 200  # Can be increase
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: true
process_results: !function utils_describe.sr_describe_process_results
metric_list:
  - metric: llm_score
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    frame_sampling: "uniform"
metadata:
  version: 1.0
