# Load StrokeRehab dataset from local
dataset_kwargs:
  use_dataset_builder: !function utils.strokerehab_load_dataset_S0001_small
task: "strokerehab_primitives"
test_split: test
output_type: generate_until
doc_to_visual: !function utils_primitives.sr_primitives_doc_to_visual
doc_to_text: !function utils_primitives.sr_primitives_doc_to_text
doc_to_target: !function utils_primitives.sr_primitives_doc_to_target
generation_kwargs:
  max_new_tokens: 200  # Can be increase
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: true
process_results: !function utils_primitives.sr_primitives_process_results
metric_list:
  - metric: edit_score
    aggregation: mean
    higher_is_better: true
  - metric: action_error_rate
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
