dataset_path: "C:/Users/AI Research/Desktop/work/BreakfastII_15fps_qvga_sync/BreakfastII_15fps_qvga_sync"
dataset_kwargs:
  use_dataset_builder: !function utils.build_breakfast_dataset
  data_dir: "C:/Users/AI Research/Desktop/work/BreakfastII_15fps_qvga_sync/BreakfastII_15fps_qvga_sync"
task: "breakfast"
test_split: test
fewshot_config:
  sampler: first_n
output_type: generate_until
doc_to_visual: !function utils.breakfast_doc_to_visual
doc_to_text: !function utils.breakfast_doc_to_text
doc_to_target: "ground_truth"
generation_kwargs:
  max_new_tokens: 60  # Can be increase
  temperature: 0.5
  top_p: 0.9
  num_beams: 2
  do_sample: true
process_results: !function utils.breakfast_process_results
metric_list:
  - metric: breakfast_score
    aggregation: !function utils.breakfast_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    frame_sampling: "uniform"
metadata:
  version: 1.0
  annotation_format: "sequential_actions"
  video_resolution: "QVGA (320x240)"
  fps: 15